name : Dockerpipeline 
on:
  push: 
    branches:
      - main
    on:
  workflow_dispatch:
  jobs:
  my_job:
    name: docker
    runs-on: ubuntu-22.04

 steps:
   - name : checkout sources code
     uses : checkout/action@v4

    - name : built image 
      uses : docker compose up 
    
