name: Dockerpipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_job:
    name: docker
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Build and start containers
        run: docker compose up -d --build
